#include "c2a_core_sample_sat.h"
#include "c2a_core_sample_components.h"
#include "Initialize.h"
#include "ClockGenerator.h"

C2aCoreSampleSat::C2aCoreSampleSat(SimulationConfig* sim_config, const GlobalEnvironment* glo_env, const int sat_id)
:Spacecraft(sim_config, glo_env, sat_id)
{
  Initialize(sim_config, glo_env, sat_id);
}

C2aCoreSampleSat::~C2aCoreSampleSat()
{
  delete components_;
}

void C2aCoreSampleSat::Initialize(SimulationConfig* sim_config, const GlobalEnvironment* glo_env, const int sat_id)
{
  components_ = new C2aCoreSampleComponents(dynamics_, structure_, local_env_, glo_env, sim_config, &clock_gen_, sat_id);
}

void C2aCoreSampleSat::LogSetup(Logger & logger)
{
  Spacecraft::LogSetup(logger);
  components_->CompoLogSetUp(logger);
}

void C2aCoreSampleSat::Update(const SimTime* sim_time)
{
  // Update Dynamics
  Spacecraft::Update(sim_time);
  // clear force and torques
  Clear();
  // Update Components
  clock_gen_.UpdateComponents(sim_time);
  // Add force and torque generated by components
  dynamics_->AddTorque_b(components_->GenerateTorque_b());
  dynamics_->AddForce_b(components_->GenerateForce_b());
}
